config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/hello_world' => 'hw#hello_world'

  resources :users
  resources :images

  root to: 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :img, ImageUploader
    belongs_to :user

    validates :title, presence: true, length: {minimum: 2}
    validates :body, presence: true
    validates :img, file_size: { less_than: 1.megabytes }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
     protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
 
  def index
    @images = Image.order('created_at DESC')
  end
 
  def show
  end
 
  def new
    @image = Image.new
  end
 
  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end
 
  def edit
  end
 
  def update
    if @image.update_attributes(image_params)
      redirect_to image_path(@image)
    else
      render :edit
    end
  end

  def destroy
    @image.destroy
    redirect_to images_path
  end
 
  private
 
  def image_params
    params.require(:image).permit(:title, :body, :img, :remove_img, :img_cache, :remote_img_url)
  end
 
  def set_image
    @image = Image.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
	  @user = User.new(user_params)
	  @user.save
	  redirect_to user_path(@user)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
	  @user = User.find(params[:id])
	  @user.update(user_params)
	  redirect_to user_path(@user)
	end

 private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end
	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hw/hello_world.html.erb

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="assets/rose_noir.jpeg" alt="First slide" >
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/rose_rouge.jpeg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/rose_jaune.jpeg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/rose_blanche.jpeg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron text-center">
    <h1>Hello World</h1><button class="btn btn-primary">primary</button>
</div>

app/views/images/_form.html.erb
<%= form_for image do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
   
    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
   
    <div>
      <%= f.label :img %>
      <%= f.file_field :img %>
    </div>
   
    <%= f.submit %>
  <% end %>
  <%= render 'shared/errors', object: image %>

app/views/images/_image.html.erb
<h2><%= link_to image.title, image_path(image) %></h2>
 
<p><%= truncate(image.body, length: 150) %></p>
 
<p><%= link_to 'Edit', edit_image_path(image), class:"lien"%></p>
<p><%= link_to 'Delete', image, method: :delete, data: { confirm: 'sure?'}, class:"lien"%></p>
<br>

app/views/images/edit.html.erb
<h1>Edit image</h1>
 
<%= render 'form', image: @image %>

app/views/images/index.html.erb
<h1>Images</h1>
 
<%= link_to 'Add image', new_image_path, class:"lien" %>
 
<%= render @images %>

app/views/images/new.html.erb
<h1>Add image</h1>
 
<%= render 'form', image: @image %>

app/views/images/show.html.erb
<%= link_to 'All images', images_path, class:"lien" %>
<h1><%= @image.title %></h1>
 
<%= image_tag(@image.img.url, alt: 'Image') if @image.img? %>
 
<p><%= @image.body %></p>
 
<p><%= link_to 'Edit', edit_image_path(@image) , class: "lien" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="/assets/application.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <title>MyMemories</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- CSS Files -->
    <link href="assets/css/material-kit.css?v=2.1.0" rel="stylesheet" />
  </head>

  <body>
  <!--
   <nav class="navbar navbar-expand-lg bg-white">
  <div class="container">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-bar navbar-kebab"></span>
    <span class="navbar-toggler-bar navbar-kebab"></span>
    <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
        -->
    <%= yield %>

   <!--   Core JS Files   -->
<script src="assets/js/core/jquery.min.js" type="text/javascript"></script>
<script src="assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
<script src="assets/js/plugins/moment.min.js"></script>
<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="assets/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
<!--  Google Maps Plugin  -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2Yno10-YTnLjjn_Vtk0V8cdcY5lC4plU"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="assets/js/plugins/bootstrap-tagsinput.js"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="assets/js/plugins/bootstrap-selectpicker.js" type="text/javascript"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="assets/js/plugins/jasny-bootstrap.min.js" type="text/javascript"></script>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
<script src="assets/js/material-kit.js?v=2.1.0" type="text/javascript"></script> 
  </body>

<footer class="footer footer-default" >
  <div class="container">
    <nav class="float-left">
      <ul>
        <li>
          <a href="https://www.youtube.com/channel/UC7N6Kz6eRPlr1EfP99Sz6Ng?view_as=subscriber/">
              Merline BELIZAIRE
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright float-right">
        &copy;
        <script>
            document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by
        <a href="https://www.instagram.com/malou__beli/" target="blank">Malou__beli</a> for a better web.
    </div>
  </div>
</footer>


</html>

app/views/shared/_form.html.erb
<%= f.label :img %>
<%= f.file_field :img %><br>
<%= f.hidden_field :img_cache %>

<% if image.img? %>
    <%= image_tag image.img.thumb.url %>
    <div>
      <%= label_tag :remove_img do %>
        Remove image
        <%= f.check_box :remove_img %>
      <% end %>
    </div>
<% end %>
<%= f.text_field :remote_img_url %>
<small>Enter URL to an image</small>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container">
    <a class="navbar-brand" href="#">MyMemories</a>
  </div>


<!-- Sign up Button -->
<button class="btn btn-round" data-toggle="modal" data-target="#signupModal">
    <i class="material-icons">assignment</i>
              <a href="../users/new" class="btn btn-primary btn-round">Sing Up</a>
</button>  <!-- log in -->
<button class="btn btn-round" data-toggle="modal" data-target="#loginModal">
    <i class="material-icons">assignment</i>
     <a href="../users/show" class="btn btn-primary btn-link btn-wd btn-lg">Login</a>
  </button>
  </nav>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="assets/rose_noir.jpeg" alt="First slide" >
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="/assets/rose_rouge.jpeg" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/rose_jaune.jpeg" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="assets/rose_blanche.jpeg" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron text-center">
    <h1>MyMemories</h1><button class="btn btn-primary">About Us</button>
</div>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
    <body>

       <h2>New User</h2>

        <form action="../images/new" style="border:1px solid #ccc">
            <label for="username"><b>Name:</b></label> <br>
            <input type="text" name="username" placeholder="Enter your Name">
            <br>
            <br>
            <label for="email"><b>Email:</b></label> <br>
            <input type="text" placeholder="Enter Email" name="email" required>
            <br>
            <br>
            <label for="psw"><b>Password:</b></label><br>
            <input type="password" placeholder="Enter Password" name="password" id="myInput">
            <input type="checkbox" onclick="myFunction()">Show Password

            <script>
            function myFunction() {
            var x = document.getElementById("myInput");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
            }
            </script>

            <br><br>
            <input type="submit" value="Submit">
        </form> 
    </body>
</html>